### ISSUE TITLE
Inquiry about Minecraft Java Edition Compatability for KubecraftAdmin

### ISSUE THREAD

**Issue by WarpWing** [erjadi/kubecraftadmin#11]
Hello! I would like to inquire if you plan to add Java Edition Compatibility? I run on MacOS so I can only use Java Edition for the time being.

**Comment by erjadi** [comment]
Hi! Thanks for the suggestion. Unfortunately my project completely relies on something called the [WebSocket Server connection](https://minecraft.gamepedia.com/Commands/wsserver) which is exclusive to Bedrock and Education editions.

As such there are no plans to make this work on Java Edition.
